sudo: false
language: node_js
node_js:
- 10

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules

install:
- yarn

script:
- node --version
- yarn lint
- yarn start:prod
- yarn lemmy

branches:
  only:
  - develop
  - master
