sudo: true
language: node_js
node_js:
- 10

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules

addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ precise main'
      key_url: https://dl.winehq.org/wine-builds/Release.key
    packages:
    - winehq-stable

install:
- yarn

script:
- node --version
- yarn lint
- yarn start:prod
- yarn lemmy

branches:
  only:
  - develop
  - master
