#ifndef EXTENSION_H
#define EXTENSION_H

#define PG_FUNC_0(NAME, RETURN_TYPE, PG_RETURN_TYPE) \
PG_FUNCTION_INFO_V1(pg_ ## NAME);\
Datum pg_ ## NAME(PG_FUNCTION_ARGS) {\
    RETURN_TYPE result = NAME();\
    PG_RETURN_ ## PG_RETURN_TYPE(result);\
}

#define PG_FUNC_1(NAME, RETURN_TYPE, PG_RETURN_TYPE, ARG0_TYPE, PG_ARG0_TYPE) \
PG_FUNCTION_INFO_V1(pg_ ## NAME); \
Datum pg_ ## NAME(PG_FUNCTION_ARGS) { \
    ARG0_TYPE arg0 = (ARG0_TYPE) PG_GETARG_ ## PG_ARG0_TYPE(0);\
    RETURN_TYPE result = NAME(arg0);\
    PG_RETURN_ ## PG_RETURN_TYPE(result);\
}

#define PG_FUNC_2(NAME, RETURN_TYPE, PG_RETURN_TYPE, ARG0_TYPE, PG_ARG0_TYPE, ARG1_TYPE, PG_ARG1_TYPE) \
PG_FUNCTION_INFO_V1(pg_ ## NAME);\
Datum pg_ ## NAME(PG_FUNCTION_ARGS) {\
    ARG0_TYPE arg0 = (ARG0_TYPE) PG_GETARG_ ## PG_ARG0_TYPE(0);\
    ARG1_TYPE arg1 = (ARG1_TYPE) PG_GETARG_ ## PG_ARG1_TYPE(1);\
    RETURN_TYPE result = NAME(arg0, arg1);\
    PG_RETURN_ ## PG_RETURN_TYPE(result);\
}

#define PG_FUNC_3(NAME, RETURN_TYPE, PG_RETURN_TYPE, ARG0_TYPE, PG_ARG0_TYPE, ARG1_TYPE, PG_ARG1_TYPE, ARG2_TYPE, PG_ARG2_TYPE) \
PG_FUNCTION_INFO_V1(pg_ ## NAME);\
Datum pg_ ## NAME(PG_FUNCTION_ARGS) {\
    ARG0_TYPE arg0 = (ARG0_TYPE) PG_GETARG_ ## PG_ARG0_TYPE(0);\
    ARG1_TYPE arg1 = (ARG1_TYPE) PG_GETARG_ ## PG_ARG1_TYPE(1);\
    ARG2_TYPE arg2 = (ARG2_TYPE) PG_GETARG_ ## PG_ARG2_TYPE(2);\
    RETURN_TYPE result = NAME(arg0, arg1, arg2);\
    PG_RETURN_ ## PG_RETURN_TYPE(result);\
}

#define PG_TRAPEZOIDAL_FUNCTION(NAME) \
PG_FUNCTION_INFO_V1(pg_##NAME);\
Datum pg_##NAME(PG_FUNCTION_ARGS) {\
    trapezoidal_function *f = NAME();\
    PG_RETURN_POINTER(f);\
}


#endif