# trapezoidal_function
/fuzzy/fstandard/all.bat
psql strzelcy -f /fuzzy/trapezoidal_function/types.sql
psql strzelcy -f /fuzzy/trapezoidal_function/operators.sql
psql strzelcy -f /fuzzy/trapezoidal_function/degree.sql
psql strzelcy -f /fuzzy/trapezoidal_function/aggregates.sql
psql strzelcy -f /fuzzy/trapezoidal_function/any_all_in.sql
psql strzelcy -f /fuzzy/trapezoidal_function/lingw.sql
#psql strzelcy -f /fuzzy/trapezoidal_function/test.sql







